# Site Settings
title: "Abdul Rahman Azam"  # Your Name or Branding
logo: /assets/profile.png
description: "AI & Blockchain Developer"  
baseurl: ""  
url: "https://abdulrahmanazam.github.io"  # Update when you have a domain

# Theme
theme: jekyll-theme-minimal

# Navigation Links
navbar-links:
  About: "index.md"
  Projects: "projects.md"
  Blog: "blog.md"
  Contact: "contact.md"

# Social Links (Icons will appear if supported)
github_username:  AbdulRahmanAzam  # Your GitHub username
linkedin_username: abdulrahmanazam  # Your LinkedIn username
leetcode_username: abdulrahmanazam # Your LeetCode username (if available)

# Footer Customization
footer-links:
  Email: "mailto:azamabdulrahman930@gmail.com"
  GitHub: "https://github.com/AbdulRahmanAzam"
  LinkedIn: "https://linkedin.com/in/abdulrahmanazam"
  LeetCode: "https://leetcode.com/abdulrahmanazam"

# SEO & Analytics
google_analytics: G-BXQRDQZLCJ
  # Replace with your Google Analytics ID (if applicable)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
